services:
  app:
    build: .
    container_name: codeflix-catalog-backend
    command: .docker/app/start.sh
    ports:
      - "4444:4444"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0.39-debian
    container_name: codeflix-catalog-db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: codeflix-catalog-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kibana:
    image: kibana:7.17.1
    container_name: codeflix-catalog-kibana
    ports:
      - "5601:5601"
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    depends_on:
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway"
