services:
  app:
    build: .
    container_name: codeflix-catalog-backend
    command: .docker/app/start.sh
    ports:
      - "4444:4444"
    volumes:
      - .:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.docker/config.json:/home/node/.docker/config.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    privileged: true
